using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.Data.Sqlite;
using Microsoft.Extensions.DependencyInjection;
using SharpInspect.Abstractions;
using SharpInspect.Runtime;
using SharpInspect.Runtime.Integrity;
using SharpInspect.Runtime.Storage;
using Xunit;
using Xunit.Sdk;

#pragma warning disable CA1416

namespace SharpInspect.Runtime.Tests;

/// <summary>
/// Windows-only acceptance coverage for the governed audit chain. Each test owns a unique
/// database directory and signing key. Database evidence is deliberately retained; cleanup
/// removes only a key whose unique name was generated by this fixture.
/// </summary>
public sealed class AuditChainAcceptanceTests
{
    [Fact]
    public async Task V103_S12_NonAnchoredWriterRechecksTailBeforeAcceptingNextOutcome()
    {
        await using var context = TestContext.Create();
        var options = new ProductionStoreOptions(context.DatabasePath)
        {
            AuditIntegrityPolicy = context.Policy with { VerificationInterval = TimeSpan.FromDays(1) }
        };
        await using var store = new SqliteCommandStore(options);
        Assert.True((await store.Initialization).Committed);
        await WaitForVerifiedAsync(store);
        await AppendAndWaitForVerifiedAsync(store, OutcomeFact());
        using (var attacker = Open(context.DatabasePath, false))
        {
            var trigger = ScalarText(attacker, "SELECT sql FROM sqlite_master WHERE name='audit_entries_immutable_update';")!;
            Execute(attacker, "DROP TRIGGER audit_entries_immutable_update;");
            Execute(attacker, "UPDATE audit_entries SET Payload='Y2hhbmdlZA==' WHERE Sequence=2;");
            Execute(attacker, trigger);
        }
        var before = CountRows(options, "command_facts");
        var rejected = await store.AppendAsync(OutcomeFact(), new StoreDeadline(TimeSpan.FromSeconds(2)));
        Assert.False(rejected.Committed);
        Assert.Equal("AuditPayloadHashMismatch", rejected.ReasonCode);
        Assert.Equal(AuditIntegrityState.Faulted, store.Integrity?.State);
        Assert.Equal(before, CountRows(options, "command_facts"));
    }

    [Fact]
    public async Task V103_S11_InvalidStorePathProjectsFaultWithoutPendingVerificationOrKeyCreation()
    {
        await using var context = TestContext.Create();
        var options = new ProductionStoreOptions(@"\\invalid-server\audit\trace.sqlite")
            { AuditIntegrityPolicy = context.Policy };
        await using var store = new SqliteCommandStore(options);
        var initialized = await store.Initialization;
        Assert.False(initialized.Committed);
        Assert.Equal("StorePathNetworkShare", initialized.ReasonCode);
        Assert.Equal(AuditIntegrityState.Faulted, store.Integrity?.State);
        Assert.Equal(initialized.ReasonCode, store.Integrity?.ReasonCode);
        Assert.False(MachineKeyExists(context.Policy));
    }

    [Fact]
    public async Task V103_S09_MinimumPolicyBudgetSupportsDefaultPageAndRejectsOversizedRequests()
    {
        await using var context = TestContext.Create();
        var policy = context.Policy with
        {
            CheckpointEveryEntries = 1,
            BackgroundVerificationEntries = 1,
            MaximumVerificationEntries = 201
        };
        Assert.Throws<ArgumentOutOfRangeException>(() => (policy with { MaximumVerificationEntries = 2 }).Validate());
        policy.Validate();
        var options = new ProductionStoreOptions(context.DatabasePath) { AuditIntegrityPolicy = policy };
        await using var store = new SqliteCommandStore(options);
        Assert.True((await store.Initialization).Committed);
        await WaitForVerifiedAsync(store);
        for (var index = 0; index < 3; index++)
            await AppendAndWaitForVerifiedAsync(store, OutcomeFact());

        var query = new SqliteAuditIntegrityQuery(options);
        var first = await query.VerifyAsync(new());
        Assert.Equal(AuditIntegrityState.Verified, first.State);
        Assert.Equal(4, first.VerifiedThroughSequence);
        var continued = await query.VerifyAsync(new(2, 200));
        Assert.Equal(AuditIntegrityState.Verified, continued.State);
        Assert.Equal(2, continued.VerifiedFromSequence);
        Assert.Equal(4, continued.VerifiedThroughSequence);
        await Assert.ThrowsAsync<ArgumentOutOfRangeException>(() => query.VerifyAsync(new(2, 201)).AsTask());
    }

    [Theory]
    [InlineData(0)]
    [InlineData(-1)]
    public async Task V103_S10_ExtraNonPositiveFactCannotEscapeChainCoverage(long position)
    {
        await using var context = TestContext.Create();
        await using (var store = new SqliteCommandStore(context.Options))
        {
            Assert.True((await store.Initialization).Committed);
            await WaitForVerifiedAsync(store);
            await AppendAndWaitForVerifiedAsync(store, OutcomeFact());
        }
        using (var attacker = Open(context.DatabasePath, false))
            Execute(attacker, @"INSERT INTO command_facts
                SELECT $position,$event,AttemptId,CorrelationId,RuntimeEpoch,EventVersion,2,OccurredAtUtc,
                    SystemPrincipalId,AuthenticatedHumanPrincipalId,CommandKind,Source,ClaimedPrincipalId,
                    ClaimedSessionId,ClaimedStepUpGrantId,1,NULL,'StopCompleted'
                FROM command_facts WHERE Position=1;", ("$position", position), ("$event", Guid.NewGuid().ToString("D")));
        var before = DatabaseHash(context.DatabasePath);
        var report = await new SqliteAuditIntegrityQuery(context.Options).VerifyAsync(new());
        Assert.Equal(AuditIntegrityState.Faulted, report.State);
        Assert.Equal("AuditUnchainedFact", report.ReasonCode);
        Assert.Equal(before, DatabaseHash(context.DatabasePath));
    }

    [Theory]
    [InlineData("audit_checkpoints", "Document")]
    [InlineData("audit_entries", "Payload")]
    public async Task V103_S08_OversizedEvidenceIsBoundedAtQueryAndWriterStartup(string table, string column)
    {
        await using var context = TestContext.Create();
        await using (var store = new SqliteCommandStore(context.Options))
        {
            Assert.True((await store.Initialization).Committed);
            await WaitForVerifiedAsync(store);
        }
        using (var attacker = Open(context.Options.DatabasePath, false))
        {
            var trigger = table + "_immutable_update";
            var definition = ScalarText(attacker, "SELECT sql FROM sqlite_master WHERE name='" + trigger + "';")!;
            Execute(attacker, "DROP TRIGGER " + trigger + ";");
            Execute(attacker, "UPDATE " + table + " SET " + column + "=$payload WHERE Sequence=1;", ("$payload", new string('A', 100000)));
            Execute(attacker, definition);
        }
        var before = DatabaseHash(context.Options.DatabasePath);
        var report = await new SqliteAuditIntegrityQuery(context.Options).VerifyAsync(new());
        Assert.Equal(AuditIntegrityState.Faulted, report.State);
        Assert.Equal("AuditEvidenceOversized", report.ReasonCode);
        await using (var reopened = new SqliteCommandStore(context.Options))
        {
            Assert.False((await reopened.Initialization.WaitAsync(TimeSpan.FromSeconds(5))).Committed);
            Assert.Equal(AuditIntegrityState.Faulted, reopened.Integrity?.State);
        }
        Assert.Equal(before, DatabaseHash(context.Options.DatabasePath));
    }

    [Fact]
    public async Task V103_S01_TransactionFactsSurviveRestartAndVerifyAgainstMachineKey()
    {
        RequireWindows();
        await using var context = TestContext.Create();

        await using (var store = new SqliteCommandStore(context.Options))
        {
            var initialized = await store.Initialization.WaitAsync(TimeSpan.FromSeconds(5));
            Assert.True(initialized.Committed, initialized.ReasonCode);
            await WaitForVerifiedAsync(store);

            for (var index = 0; index < 3; index++)
                await AppendAndWaitForVerifiedAsync(store, OutcomeFact());

            var report = await new SqliteAuditIntegrityQuery(context.Options)
                .VerifyAsync(new AuditVerificationRequest(0, 200));
            Assert.Equal(AuditIntegrityState.Verified, report.State);
            Assert.Equal(1, report.VerifiedFromSequence);
            Assert.Equal(report.ThroughSequence, report.VerifiedThroughSequence);
            Assert.Equal(3, CountRows(context.Options, "command_facts"));
        }

        await using var restarted = new SqliteCommandStore(context.Options);
        var restartResult = await restarted.Initialization.WaitAsync(TimeSpan.FromSeconds(5));
        Assert.True(restartResult.Committed, restartResult.ReasonCode);
        var restartedReport = await WaitForVerifiedAsync(restarted);
        Assert.Equal(AuditIntegrityState.Verified, restartedReport.State);
        Assert.Equal(restartedReport.ThroughSequence, restartedReport.VerifiedThroughSequence);

        var queryReport = await new SqliteAuditIntegrityQuery(context.Options)
            .VerifyAsync(new AuditVerificationRequest(0, 200));
        Assert.Equal(AuditIntegrityState.Verified, queryReport.State);
        Assert.Equal(restartedReport.ThroughSequence, queryReport.ThroughSequence);
    }

    [Theory]
    [InlineData("fact-reason")]
    [InlineData("chain-payload")]
    [InlineData("missing-entry")]
    [InlineData("reordered-sequence")]
    [InlineData("truncated-before-checkpoint")]
    [InlineData("checkpoint-signature")]
    public async Task V103_S02_OfflineTamperIsFaultedWithoutReadOnlyDatabaseMutation(string tamperCase)
    {
        RequireWindows();
        await using var context = TestContext.Create();

        await using (var store = new SqliteCommandStore(context.Options))
        {
            var initialized = await store.Initialization.WaitAsync(TimeSpan.FromSeconds(5));
            Assert.True(initialized.Committed, initialized.ReasonCode);
            await WaitForVerifiedAsync(store);
            for (var index = 0; index < 3; index++)
                await AppendAndWaitForVerifiedAsync(store, OutcomeFact());
        }

        ApplyTamper(context.Options.DatabasePath, tamperCase);
        var beforeReadOnlyVerify = DatabaseHash(context.Options.DatabasePath);
        var report = await new SqliteAuditIntegrityQuery(context.Options)
            .VerifyAsync(new AuditVerificationRequest(0, 200));

        Assert.Equal(AuditIntegrityState.Faulted, report.State);
        Assert.False(string.IsNullOrWhiteSpace(report.ReasonCode));
        Assert.Equal(beforeReadOnlyVerify, DatabaseHash(context.Options.DatabasePath));
    }

    [Fact]
    public async Task V103_S03_GovernedPolicyRejectsSchemaOneWithoutCreatingKeyOrChangingBytes()
    {
        RequireWindows();
        await using var context = TestContext.Create();
        var legacyOptions = new ProductionStoreOptions(context.Options.DatabasePath)
        {
            CommitTimeout = context.Options.CommitTimeout,
            QueryTimeout = context.Options.QueryTimeout,
            QueueCapacity = context.Options.QueueCapacity
        };

        await using (var legacyStore = new SqliteCommandStore(legacyOptions))
        {
            var initialized = await legacyStore.Initialization.WaitAsync(TimeSpan.FromSeconds(5));
            Assert.True(initialized.Committed, initialized.ReasonCode);
            var written = await legacyStore.AppendAsync(OutcomeFact(),
                new StoreDeadline(TimeSpan.FromSeconds(1)));
            Assert.True(written.Committed, written.ReasonCode);
        }

        using (var check = Open(context.Options.DatabasePath, readOnly: true))
            Assert.Equal(1L, ScalarInt64(check, "PRAGMA user_version;"));

        Assert.False(MachineKeyExists(context.Policy));
        var before = DatabaseHash(context.Options.DatabasePath);
        await using var governedStore = new SqliteCommandStore(context.Options);
        var result = await governedStore.Initialization.WaitAsync(TimeSpan.FromSeconds(5));

        Assert.False(result.Committed);
        Assert.Equal("AuditGovernedMigrationRequired", result.ReasonCode);
        Assert.False(MachineKeyExists(context.Policy));
        Assert.Equal(before, DatabaseHash(context.Options.DatabasePath));
    }

    [Fact]
    public async Task V103_S04_DeletingMachineKeyMakesSchemaTwoReopenFailWithoutRecreation()
    {
        RequireWindows();
        await using var context = TestContext.Create();

        await using (var store = new SqliteCommandStore(context.Options))
        {
            var initialized = await store.Initialization.WaitAsync(TimeSpan.FromSeconds(5));
            Assert.True(initialized.Committed, initialized.ReasonCode);
            await WaitForVerifiedAsync(store);
        }

        var before = DatabaseHash(context.Options.DatabasePath);
        DeleteMachineKey(context.Policy);
        Assert.False(MachineKeyExists(context.Policy));

        await using var reopened = new SqliteCommandStore(context.Options);
        var result = await reopened.Initialization.WaitAsync(TimeSpan.FromSeconds(5));

        Assert.False(result.Committed);
        Assert.Equal("AuditSigningKeyMissing", result.ReasonCode);
        Assert.False(MachineKeyExists(context.Policy));
        Assert.Equal(before, DatabaseHash(context.Options.DatabasePath));
    }

    [Fact]
    public async Task V103_S05_ExistingMachineKeyAndEmptyDatabaseRejectOrphanProvisioning()
    {
        RequireWindows();
        await using var context = TestContext.Create();
        string keyId;
        using (var existing = WindowsMachineAuditKey.Open(context.Policy, allowCreation: true, out var created))
        {
            Assert.True(created);
            keyId = existing.KeyId;
        }

        Assert.True(MachineKeyExists(context.Policy));
        await using var store = new SqliteCommandStore(context.Options);
        var result = await store.Initialization.WaitAsync(TimeSpan.FromSeconds(5));

        Assert.False(result.Committed);
        Assert.Equal("AuditSigningKeyProvisioningConflict", result.ReasonCode);
        Assert.True(MachineKeyExists(context.Policy));
        using var reopened = WindowsMachineAuditKey.Open(context.Policy, allowCreation: false, out var reopenedCreated);
        Assert.False(reopenedCreated);
        Assert.Equal(keyId, reopened.KeyId);
    }

    [Fact]
    public async Task V103_S06_GovernedAuditChangesRejectAdministratorInputButPersistAndVerify()
    {
        RequireWindows();
        await using var context = TestContext.Create();
        var services = new ServiceCollection();
        services.AddSharpInspectRuntime(TimeSpan.FromMilliseconds(20));
        services.AddSharpInspectSqliteRuntime(context.Options);

        await using var provider = services.BuildServiceProvider();
        var store = provider.GetRequiredService<SqliteCommandStore>();
        var initialized = await store.Initialization.WaitAsync(TimeSpan.FromSeconds(5));
        Assert.True(initialized.Committed, initialized.ReasonCode);
        await WaitForVerifiedAsync(store);
        var runtime = provider.GetRequiredService<IStationRuntime>();

        foreach (var change in Enum.GetValues<GovernedAuditChangeKind>())
        {
            var command = new GovernedAuditChangeCommand(Guid.NewGuid(),
                new CommandInvocation(CommandSource.PhysicalConsole, "Administrator", Guid.NewGuid(), Guid.NewGuid()),
                change);
            var outcome = await runtime.SubmitAsync(command);

            Assert.Equal(CommandDisposition.Rejected, outcome.Disposition);
            Assert.Equal("AuthorizationUnavailable", outcome.ReasonCode);
            Assert.Equal(AuditPersistence.Persisted, outcome.Audit);
            Assert.NotNull(outcome.AttemptId);
            await WaitForVerifiedAsync(store);
        }

        var report = await new SqliteAuditIntegrityQuery(context.Options)
            .VerifyAsync(new AuditVerificationRequest(0, 200));
        Assert.Equal(AuditIntegrityState.Verified, report.State);

        var page = await new SqliteCommandTraceQuery(context.Options)
            .QueryAsync(new CommandTraceFilter(PageSize: 10));
        Assert.Equal(4, page.Records.Count);
        Assert.All(page.Records, record =>
        {
            Assert.Equal(CommandDisposition.Rejected, record.Disposition);
            Assert.Equal("AuthorizationUnavailable", record.ReasonCode);
            Assert.Equal("Administrator", record.ClaimedPrincipalId);
        });
        Assert.Equal(new[] { AuditedCommandKind.RotateSigningKey, AuditedCommandKind.RetireSigningKey,
            AuditedCommandKind.CorrectHistoricalFact, AuditedCommandKind.DeleteEvidence }, page.Records.Select(r => r.CommandKind));
    }

    [Fact]
    public async Task V103_S07_AbortDuringAuditEntryInsertRollsBackFactsAttemptsChainAndCheckpoint()
    {
        RequireWindows();
        await using var context = TestContext.Create();
        await using var store = new SqliteCommandStore(context.Options);
        var initialized = await store.Initialization.WaitAsync(TimeSpan.FromSeconds(5));
        Assert.True(initialized.Committed, initialized.ReasonCode);
        await WaitForVerifiedAsync(store);

        var beforeAttempts = CountRows(context.Options, "command_attempts");
        var beforeFacts = CountRows(context.Options, "command_facts");
        var beforeEntries = CountRows(context.Options, "audit_entries");
        var beforeCheckpoints = CountRows(context.Options, "audit_checkpoints");
        var trigger = "test_abort_audit_entry_" + Guid.NewGuid().ToString("N");
        using var injector = Open(context.Options.DatabasePath, readOnly: false);
        Execute(injector, $@"
            CREATE TRIGGER {trigger}
            BEFORE INSERT ON audit_entries
            BEGIN
                SELECT RAISE(ABORT, 'TestAuditEntryAbort');
            END;");

        var failed = await store.AppendAsync(OutcomeFact(), new StoreDeadline(TimeSpan.FromSeconds(1)));
        Assert.False(failed.Committed);
        Assert.Equal("TraceStoreConstraint", failed.ReasonCode);
        Assert.Equal(beforeAttempts, CountRows(context.Options, "command_attempts"));
        Assert.Equal(beforeFacts, CountRows(context.Options, "command_facts"));
        Assert.Equal(beforeEntries, CountRows(context.Options, "audit_entries"));
        Assert.Equal(beforeCheckpoints, CountRows(context.Options, "audit_checkpoints"));

        Execute(injector, $"DROP TRIGGER {trigger};");
        var recovered = await AppendAndWaitForVerifiedAsync(store, OutcomeFact());
        Assert.NotNull(recovered);
        var report = await new SqliteAuditIntegrityQuery(context.Options)
            .VerifyAsync(new AuditVerificationRequest(0, 200));
        Assert.Equal(AuditIntegrityState.Verified, report.State);
    }

    private static async Task<AuditIntegrityReport> WaitForVerifiedAsync(SqliteCommandStore store,
        TimeSpan? timeout = null)
    {
        var deadline = DateTime.UtcNow + (timeout ?? TimeSpan.FromSeconds(5));
        while (DateTime.UtcNow < deadline)
        {
            var report = store.Integrity;
            if (report is { State: AuditIntegrityState.Verified }) return report;
            if (report?.State == AuditIntegrityState.Faulted)
                throw new XunitException($"Audit integrity faulted: {report.ReasonCode}");
            await Task.Delay(25);
        }

        throw new XunitException($"Audit integrity did not become Verified. Last state: {store.Integrity?.State}, " +
            $"reason: {store.Integrity?.ReasonCode}");
    }

    private static async Task<StoreWriteResult> AppendAndWaitForVerifiedAsync(SqliteCommandStore store,
        CommandAuditFact fact)
    {
        var result = await store.AppendAsync(fact, new StoreDeadline(TimeSpan.FromSeconds(2)));
        Assert.True(result.Committed, result.ReasonCode);
        await WaitForVerifiedAsync(store);
        return result;
    }

    private static CommandAuditFact OutcomeFact() =>
        new(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), DateTimeOffset.UtcNow,
            AuditedCommandKind.GracefulProductionStop, CommandSource.PhysicalConsole,
            "claimed/operator", Guid.NewGuid(), Guid.NewGuid(), CommandAuditPhase.Outcome,
            CommandDisposition.Accepted, "StopAdmitted");

    private static void ApplyTamper(string databasePath, string tamperCase)
    {
        using var connection = Open(databasePath, readOnly: false);
        switch (tamperCase)
        {
            case "fact-reason":
                Execute(connection, "DROP TRIGGER command_facts_immutable_update;");
                Execute(connection, "UPDATE command_facts SET ReasonCode='TamperedReason' WHERE Position=1;");
                break;
            case "chain-payload":
                Execute(connection, "DROP TRIGGER audit_entries_immutable_update;");
                Execute(connection, "UPDATE audit_entries SET Payload=$payload WHERE Sequence=2;",
                    ("$payload", Convert.ToBase64String(Encoding.UTF8.GetBytes("tampered-payload"))));
                break;
            case "missing-entry":
                Execute(connection, "DROP TRIGGER audit_entries_immutable_delete;");
                Execute(connection, "DELETE FROM audit_entries WHERE Sequence=2;");
                break;
            case "reordered-sequence":
                Execute(connection, "DROP TRIGGER audit_entries_immutable_update;");
                Execute(connection, "UPDATE audit_entries SET Sequence=99 WHERE Sequence=2;");
                break;
            case "truncated-before-checkpoint":
                Execute(connection, "DROP TRIGGER audit_entries_immutable_delete;");
                Execute(connection, "DELETE FROM audit_entries WHERE Sequence>=3;");
                break;
            case "checkpoint-signature":
                Execute(connection, "DROP TRIGGER audit_checkpoints_immutable_update;");
                var document = ScalarText(connection,
                    "SELECT Document FROM audit_checkpoints ORDER BY Sequence DESC LIMIT 1;");
                var checkpoint = JsonSerializer.Deserialize<AuditCheckpoint>(document!)!;
                var signature = Convert.FromBase64String(checkpoint.SignatureBase64);
                signature[0] ^= 0x01;
                var tampered = JsonSerializer.Serialize(checkpoint with
                {
                    SignatureBase64 = Convert.ToBase64String(signature)
                });
                Execute(connection, "UPDATE audit_checkpoints SET Document=$document WHERE Sequence=$sequence;",
                    ("$document", tampered), ("$sequence", checkpoint.Sequence));
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(tamperCase), tamperCase, null);
        }
    }

    private static string DatabaseHash(string databasePath) =>
        Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(databasePath)));

    private static long CountRows(ProductionStoreOptions options, string table)
    {
        using var connection = Open(options.DatabasePath, readOnly: true);
        return ScalarInt64(connection, $"SELECT COUNT(*) FROM {table};");
    }

    private static SqliteConnection Open(string databasePath, bool readOnly)
    {
        var builder = new SqliteConnectionStringBuilder
        {
            DataSource = databasePath,
            Mode = readOnly ? SqliteOpenMode.ReadOnly : SqliteOpenMode.ReadWrite,
            Cache = SqliteCacheMode.Private,
            Pooling = false
        };
        var connection = new SqliteConnection(builder.ToString());
        connection.Open();
        return connection;
    }

    private static void Execute(SqliteConnection connection, string sql,
        params (string Name, object? Value)[] parameters)
    {
        using var command = connection.CreateCommand();
        command.CommandText = sql;
        foreach (var (name, value) in parameters)
            command.Parameters.AddWithValue(name, value ?? DBNull.Value);
        command.ExecuteNonQuery();
    }

    private static object? Scalar(SqliteConnection connection, string sql)
    {
        using var command = connection.CreateCommand();
        command.CommandText = sql;
        return command.ExecuteScalar();
    }

    private static long ScalarInt64(SqliteConnection connection, string sql) => Convert.ToInt64(Scalar(connection, sql));

    private static string? ScalarText(SqliteConnection connection, string sql) => Scalar(connection, sql)?.ToString();

    private static bool MachineKeyExists(AuditIntegrityPolicy policy) =>
        File.Exists(WindowsMachineAuditKey.GetKeyPath(policy));

    private static void DeleteMachineKey(AuditIntegrityPolicy policy)
    {
        try
        {
            var keyPath = WindowsMachineAuditKey.GetKeyPath(policy);
            if (File.Exists(keyPath)) File.Delete(keyPath);
        }
        catch (UnauthorizedAccessException)
        {
            // The acceptance result must retain the directory evidence even if cleanup is denied.
        }
        catch (IOException)
        {
            // A failed run must retain its evidence if the protected key file is still open.
        }
    }

    private static void RequireWindows()
    {
        if (!OperatingSystem.IsWindows())
            throw SkipException.ForSkip("Audit-chain acceptance requires Windows protected audit keys.");
    }

    private sealed class TestContext : IAsyncDisposable
    {
        private TestContext(string directoryPath, string databasePath, string keyName,
            AuditIntegrityPolicy policy, ProductionStoreOptions options)
        {
            DirectoryPath = directoryPath;
            DatabasePath = databasePath;
            KeyName = keyName;
            Policy = policy;
            Options = options;
        }

        public string DirectoryPath { get; }
        public string DatabasePath { get; }
        public string KeyName { get; }
        public AuditIntegrityPolicy Policy { get; }
        public ProductionStoreOptions Options { get; }

        public static TestContext Create()
        {
            var directoryPath = Path.Combine(Path.GetTempPath(), "SharpInspect.Runtime.Tests", "V103-AuditChain",
                Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(directoryPath);
            var databasePath = Path.Combine(directoryPath, "trace.sqlite");
            var keyName = "SharpInspect.Test.AuditChain." + Guid.NewGuid().ToString("N");
            var policy = new AuditIntegrityPolicy("TestStation", "v1", keyName)
            {
                AllowInitialKeyCreation = true,
                CheckpointEveryEntries = 2,
                VerificationInterval = TimeSpan.FromSeconds(1)
            };
            var options = new ProductionStoreOptions(databasePath)
            {
                AuditIntegrityPolicy = policy,
                CommitTimeout = TimeSpan.FromSeconds(2),
                QueryTimeout = TimeSpan.FromSeconds(2),
                QueueCapacity = 8
            };
            return new TestContext(directoryPath, databasePath, keyName, policy, options);
        }

        public ValueTask DisposeAsync()
        {
            DeleteMachineKey(Policy);
            // Database directories are intentionally retained as acceptance evidence.
            return ValueTask.CompletedTask;
        }
    }
}

#pragma warning restore CA1416
